spring:
  datasource:
    url: jdbc:mysql://mysql:3306/article
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

